### ISSUE TITLE
No validation is performed when saving a Recipe

### ISSUE THREAD

**Issue by savage-engineer** [OpenBrews/OpenBrews#62] opened 2016-10-13 13:55 UTC
When creating or saving a Recipe the app does not appear to perform any validation on the fields. Of particular note - you can create a recipe with an empty string as it's name. Saving this then results in a blank button, which probably isn't an intended bit of functionality.

**Comment by MichaelWashburnJr** [comment] 2016-10-13 15:22
This is the same as #51 I believe, correct?

**Comment by icyflame** [comment] 2016-10-13 15:37
Closing this issue. This is a duplicate of #51. @savage-engineer Thanks for reporting! Please do search issues dashboard for the issue before creating a new one :slightly_smiling_face:

**Closed as completed by icyflame** 2016-10-13 15:37 UTC
Labels: duplicate

**Comment by savage-engineer** [comment] 2016-10-13 15:54
Oops, missed that one!
